/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorResponse,
  CreateProblem201,
  CreateProblemRequest,
  DeleteProblem200,
  GetProblem200,
  GetProblems200,
  GetProblemsParams,
  UpdateProblem200,
  UpdateProblemRequest,
} from "../discodeApi.schemas.ts";

import { customFetch } from ".././fetcher.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createProblemResponse201 = {
  data: CreateProblem201;
  status: 201;
};

export type createProblemResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type createProblemResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type createProblemResponse403 = {
  data: ApiErrorResponse;
  status: 403;
};

export type createProblemResponseSuccess = createProblemResponse201 & {
  headers: Headers;
};
export type createProblemResponseError = (
  | createProblemResponse400
  | createProblemResponse401
  | createProblemResponse403
) & {
  headers: Headers;
};

export type createProblemResponse =
  | createProblemResponseSuccess
  | createProblemResponseError;

export const getCreateProblemUrl = () => {
  return `/api/v1/problems`;
};

/**
 * @summary Create a new problem
 */
export const createProblem = async (
  createProblemRequest?: CreateProblemRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<createProblemResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<createProblemResponse>(getCreateProblemUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(createProblemRequest),
  });
};

export const getCreateProblemMutationKey = () => ["createProblem"] as const;

export const getCreateProblemMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProblem>>,
    TError,
    CreateProblemMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProblem>>,
  TError,
  CreateProblemMutationVariables,
  TContext
> => {
  const mutationKey = getCreateProblemMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProblem>>,
    CreateProblemMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createProblem(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProblemMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProblem>>
>;
export type CreateProblemMutationBody = CreateProblemRequest | undefined;
export type CreateProblemMutationError = ApiErrorResponse;
export type CreateProblemMutationVariables = { data?: CreateProblemRequest };

/**
 * @summary Create a new problem
 */
export const useCreateProblem = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProblem>>,
      TError,
      CreateProblemMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProblem>>,
  TError,
  CreateProblemMutationVariables,
  TContext
> => {
  return useMutation(getCreateProblemMutationOptions(options), queryClient);
};
export type getProblemsResponse200 = {
  data: GetProblems200;
  status: 200;
};

export type getProblemsResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type getProblemsResponseSuccess = getProblemsResponse200 & {
  headers: Headers;
};
export type getProblemsResponseError = getProblemsResponse400 & {
  headers: Headers;
};

export type getProblemsResponse =
  | getProblemsResponseSuccess
  | getProblemsResponseError;

export const getGetProblemsUrl = (params?: GetProblemsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/problems?${stringifiedParams}`
    : `/api/v1/problems`;
};

/**
 * @summary Get problems with optional filtering and pagination
 */
export const getProblems = async (
  params?: GetProblemsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<getProblemsResponse> => {
  return customFetch<getProblemsResponse>(getGetProblemsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetProblemsQueryKey = (params?: GetProblemsParams) => {
  return [`/api/v1/problems`, ...(params ? [params] : [])] as const;
};

export const getGetProblemsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProblems>>,
  TError = ApiErrorResponse,
>(
  params?: GetProblemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProblemsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProblems>>> = ({
    signal,
  }) => getProblems(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProblems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProblemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProblems>>
>;
export type GetProblemsQueryError = ApiErrorResponse;

export function useGetProblems<
  TData = Awaited<ReturnType<typeof getProblems>>,
  TError = ApiErrorResponse,
>(
  params: undefined | GetProblemsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProblems>>,
          TError,
          Awaited<ReturnType<typeof getProblems>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProblems<
  TData = Awaited<ReturnType<typeof getProblems>>,
  TError = ApiErrorResponse,
>(
  params?: GetProblemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProblems>>,
          TError,
          Awaited<ReturnType<typeof getProblems>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProblems<
  TData = Awaited<ReturnType<typeof getProblems>>,
  TError = ApiErrorResponse,
>(
  params?: GetProblemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get problems with optional filtering and pagination
 */

export function useGetProblems<
  TData = Awaited<ReturnType<typeof getProblems>>,
  TError = ApiErrorResponse,
>(
  params?: GetProblemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProblemsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProblemResponse200 = {
  data: GetProblem200;
  status: 200;
};

export type getProblemResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type getProblemResponseSuccess = getProblemResponse200 & {
  headers: Headers;
};
export type getProblemResponseError = getProblemResponse404 & {
  headers: Headers;
};

export type getProblemResponse =
  | getProblemResponseSuccess
  | getProblemResponseError;

export const getGetProblemUrl = (problemId: string) => {
  return `/api/v1/problems/${problemId}`;
};

/**
 * @summary Get a problem by ID
 */
export const getProblem = async (
  problemId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<getProblemResponse> => {
  return customFetch<getProblemResponse>(getGetProblemUrl(problemId), {
    ...options,
    method: "GET",
  });
};

export const getGetProblemQueryKey = (problemId: string) => {
  return [`/api/v1/problems/${problemId}`] as const;
};

export const getGetProblemQueryOptions = <
  TData = Awaited<ReturnType<typeof getProblem>>,
  TError = ApiErrorResponse,
>(
  problemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblem>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProblemQueryKey(problemId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProblem>>> = ({
    signal,
  }) => getProblem(problemId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: problemId !== null && problemId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProblem>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProblemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProblem>>
>;
export type GetProblemQueryError = ApiErrorResponse;

export function useGetProblem<
  TData = Awaited<ReturnType<typeof getProblem>>,
  TError = ApiErrorResponse,
>(
  problemId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblem>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProblem>>,
          TError,
          Awaited<ReturnType<typeof getProblem>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProblem<
  TData = Awaited<ReturnType<typeof getProblem>>,
  TError = ApiErrorResponse,
>(
  problemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblem>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProblem>>,
          TError,
          Awaited<ReturnType<typeof getProblem>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProblem<
  TData = Awaited<ReturnType<typeof getProblem>>,
  TError = ApiErrorResponse,
>(
  problemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblem>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a problem by ID
 */

export function useGetProblem<
  TData = Awaited<ReturnType<typeof getProblem>>,
  TError = ApiErrorResponse,
>(
  problemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProblem>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProblemQueryOptions(problemId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateProblemResponse200 = {
  data: UpdateProblem200;
  status: 200;
};

export type updateProblemResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type updateProblemResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type updateProblemResponse403 = {
  data: ApiErrorResponse;
  status: 403;
};

export type updateProblemResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type updateProblemResponseSuccess = updateProblemResponse200 & {
  headers: Headers;
};
export type updateProblemResponseError = (
  | updateProblemResponse400
  | updateProblemResponse401
  | updateProblemResponse403
  | updateProblemResponse404
) & {
  headers: Headers;
};

export type updateProblemResponse =
  | updateProblemResponseSuccess
  | updateProblemResponseError;

export const getUpdateProblemUrl = (problemId: string) => {
  return `/api/v1/problems/${problemId}`;
};

/**
 * @summary Update a problem
 */
export const updateProblem = async (
  problemId: string,
  updateProblemRequest?: UpdateProblemRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<updateProblemResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<updateProblemResponse>(getUpdateProblemUrl(problemId), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(updateProblemRequest),
  });
};

export const getUpdateProblemMutationKey = () => ["updateProblem"] as const;

export const getUpdateProblemMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProblem>>,
    TError,
    UpdateProblemMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProblem>>,
  TError,
  UpdateProblemMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateProblemMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProblem>>,
    UpdateProblemMutationVariables
  > = (props) => {
    const { problemId, data } = props ?? {};

    return updateProblem(problemId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProblemMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProblem>>
>;
export type UpdateProblemMutationBody = UpdateProblemRequest | undefined;
export type UpdateProblemMutationError = ApiErrorResponse;
export type UpdateProblemMutationVariables = {
  problemId: string;
  data?: UpdateProblemRequest;
};

/**
 * @summary Update a problem
 */
export const useUpdateProblem = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProblem>>,
      TError,
      UpdateProblemMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProblem>>,
  TError,
  UpdateProblemMutationVariables,
  TContext
> => {
  return useMutation(getUpdateProblemMutationOptions(options), queryClient);
};
export type deleteProblemResponse200 = {
  data: DeleteProblem200;
  status: 200;
};

export type deleteProblemResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type deleteProblemResponse403 = {
  data: ApiErrorResponse;
  status: 403;
};

export type deleteProblemResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type deleteProblemResponseSuccess = deleteProblemResponse200 & {
  headers: Headers;
};
export type deleteProblemResponseError = (
  | deleteProblemResponse401
  | deleteProblemResponse403
  | deleteProblemResponse404
) & {
  headers: Headers;
};

export type deleteProblemResponse =
  | deleteProblemResponseSuccess
  | deleteProblemResponseError;

export const getDeleteProblemUrl = (problemId: string) => {
  return `/api/v1/problems/${problemId}`;
};

/**
 * @summary Delete a problem
 */
export const deleteProblem = async (
  problemId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<deleteProblemResponse> => {
  return customFetch<deleteProblemResponse>(getDeleteProblemUrl(problemId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteProblemMutationKey = () => ["deleteProblem"] as const;

export const getDeleteProblemMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProblem>>,
    TError,
    DeleteProblemMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProblem>>,
  TError,
  DeleteProblemMutationVariables,
  TContext
> => {
  const mutationKey = getDeleteProblemMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProblem>>,
    DeleteProblemMutationVariables
  > = (props) => {
    const { problemId } = props ?? {};

    return deleteProblem(problemId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProblemMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProblem>>
>;

export type DeleteProblemMutationError = ApiErrorResponse;
export type DeleteProblemMutationVariables = { problemId: string };

/**
 * @summary Delete a problem
 */
export const useDeleteProblem = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProblem>>,
      TError,
      DeleteProblemMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProblem>>,
  TError,
  DeleteProblemMutationVariables,
  TContext
> => {
  return useMutation(getDeleteProblemMutationOptions(options), queryClient);
};
