/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type {
  CreateProblem201,
  DeleteProblem200,
  GetProblem200,
  GetProblems200,
  UpdateProblem200,
} from "../discodeApi.schemas";

export const getCreateProblemResponseMock = (
  overrideResponse: Partial<Extract<CreateProblem201, object>> = {},
): CreateProblem201 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    problem_id: faker.string.uuid(),
    title: faker.string.alpha({ length: { min: 1, max: 200 } }),
    markdown_key: faker.string.alpha({ length: { min: 1, max: 20 } }),
    test_keys: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 1, max: 20 } })),
    difficulty: faker.helpers.arrayElement(["easy", "medium", "hard"] as const),
    tags: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    created_by: faker.number.int({ min: 0 }),
    created_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
    updated_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getGetProblemsResponseMock = (
  overrideResponse: Partial<Extract<GetProblems200, object>> = {},
): GetProblems200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    problems: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      ...{
        problem_id: faker.string.uuid(),
        title: faker.string.alpha({ length: { min: 1, max: 200 } }),
        markdown_key: faker.string.alpha({ length: { min: 1, max: 20 } }),
        test_keys: Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => faker.string.alpha({ length: { min: 1, max: 20 } })),
        difficulty: faker.helpers.arrayElement([
          "easy",
          "medium",
          "hard",
        ] as const),
        tags: Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
        created_by: faker.number.int({ min: 0 }),
        created_at: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          faker.date.past().toISOString().slice(0, 19) + "Z",
        ]),
        updated_at: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          faker.date.past().toISOString().slice(0, 19) + "Z",
        ]),
      },
      ...{
        creator_username: faker.string.alpha({ length: { min: 10, max: 30 } }),
      },
    })),
    totalProblems: faker.number.int(),
    totalPages: faker.number.int(),
    currentPage: faker.number.int(),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getGetProblemResponseMock = (
  overrideResponse: Partial<Extract<GetProblem200, object>> = {},
): GetProblem200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    ...{
      problem_id: faker.string.uuid(),
      title: faker.string.alpha({ length: { min: 1, max: 200 } }),
      markdown_key: faker.string.alpha({ length: { min: 1, max: 20 } }),
      test_keys: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { min: 1, max: 20 } })),
      difficulty: faker.helpers.arrayElement([
        "easy",
        "medium",
        "hard",
      ] as const),
      tags: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
      created_by: faker.number.int({ min: 0 }),
      created_at: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        faker.date.past().toISOString().slice(0, 19) + "Z",
      ]),
      updated_at: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        faker.date.past().toISOString().slice(0, 19) + "Z",
      ]),
    },
    ...{
      creator_username: faker.string.alpha({ length: { min: 10, max: 30 } }),
    },
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getUpdateProblemResponseMock = (
  overrideResponse: Partial<Extract<UpdateProblem200, object>> = {},
): UpdateProblem200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    problem_id: faker.string.uuid(),
    title: faker.string.alpha({ length: { min: 1, max: 200 } }),
    markdown_key: faker.string.alpha({ length: { min: 1, max: 20 } }),
    test_keys: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 1, max: 20 } })),
    difficulty: faker.helpers.arrayElement(["easy", "medium", "hard"] as const),
    tags: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
    created_by: faker.number.int({ min: 0 }),
    created_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
    updated_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getDeleteProblemResponseMock = (
  overrideResponse: Partial<Extract<DeleteProblem200, object>> = {},
): DeleteProblem200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});
