/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type {
  ChangeUserRole200,
  GetLoggedUserProfile200,
  GetUserProfile200,
  GetUserRole200,
  LoginUser200,
  RegisterUser201,
  UpdateProfile200,
} from "../discodeApi.schemas";

export const getRegisterUserResponseMock = (
  overrideResponse: Partial<Extract<RegisterUser201, object>> = {},
): RegisterUser201 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getLoginUserResponseMock = (
  overrideResponse: Partial<Extract<LoginUser200, object>> = {},
): LoginUser200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getGetLoggedUserProfileResponseMock = (
  overrideResponse: Partial<Extract<GetLoggedUserProfile200, object>> = {},
): GetLoggedUserProfile200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    user_id: faker.number.int({ min: 0 }),
    username: faker.string.alpha({ length: { min: 10, max: 30 } }),
    email: faker.internet.email(),
    bio: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    avatar_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    role: faker.helpers.arrayElement([
      "superadmin",
      "admin",
      "moderator",
      "normal",
    ] as const),
    created_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getUpdateProfileResponseMock = (
  overrideResponse: Partial<Extract<UpdateProfile200, object>> = {},
): UpdateProfile200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getGetUserProfileResponseMock = (
  overrideResponse: Partial<Extract<GetUserProfile200, object>> = {},
): GetUserProfile200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    user_id: faker.number.int({ min: 0 }),
    username: faker.string.alpha({ length: { min: 10, max: 30 } }),
    email: faker.internet.email(),
    bio: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    avatar_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    role: faker.helpers.arrayElement([
      "superadmin",
      "admin",
      "moderator",
      "normal",
    ] as const),
    created_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getGetUserRoleResponseMock = (
  overrideResponse: Partial<Extract<GetUserRole200, object>> = {},
): GetUserRole200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    role: faker.helpers.arrayElement([
      "superadmin",
      "admin",
      "moderator",
      "normal",
    ] as const),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getChangeUserRoleResponseMock = (
  overrideResponse: Partial<Extract<ChangeUserRole200, object>> = {},
): ChangeUserRole200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});
