/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorResponse,
  ChangeRoleRequest,
  ChangeUserRole200,
  GetLoggedUserProfile200,
  GetUserProfile200,
  GetUserRole200,
  LoginRequest,
  LoginUser200,
  RegisterRequest,
  RegisterUser201,
  UpdateProfile200,
  UpdateProfileRequest,
} from "../discodeApi.schemas.ts";

import { customFetch } from ".././fetcher.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type registerUserResponse201 = {
  data: RegisterUser201;
  status: 201;
};

export type registerUserResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type registerUserResponse409 = {
  data: ApiErrorResponse;
  status: 409;
};

export type registerUserResponseSuccess = registerUserResponse201 & {
  headers: Headers;
};
export type registerUserResponseError = (
  | registerUserResponse400
  | registerUserResponse409
) & {
  headers: Headers;
};

export type registerUserResponse =
  | registerUserResponseSuccess
  | registerUserResponseError;

export const getRegisterUserUrl = () => {
  return `/api/v1/users/register`;
};

/**
 * @summary Register a new user
 */
export const registerUser = async (
  registerRequest?: RegisterRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<registerUserResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<registerUserResponse>(getRegisterUserUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(registerRequest),
  });
};

export const getRegisterUserMutationKey = () => ["registerUser"] as const;

export const getRegisterUserMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    RegisterUserMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  RegisterUserMutationVariables,
  TContext
> => {
  const mutationKey = getRegisterUserMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    RegisterUserMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return registerUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerUser>>
>;
export type RegisterUserMutationBody = RegisterRequest | undefined;
export type RegisterUserMutationError = ApiErrorResponse;
export type RegisterUserMutationVariables = { data?: RegisterRequest };

/**
 * @summary Register a new user
 */
export const useRegisterUser = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerUser>>,
      TError,
      RegisterUserMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  RegisterUserMutationVariables,
  TContext
> => {
  return useMutation(getRegisterUserMutationOptions(options), queryClient);
};
export type loginUserResponse200 = {
  data: LoginUser200;
  status: 200;
};

export type loginUserResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type loginUserResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type loginUserResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type loginUserResponseSuccess = loginUserResponse200 & {
  headers: Headers;
};
export type loginUserResponseError = (
  | loginUserResponse400
  | loginUserResponse401
  | loginUserResponse404
) & {
  headers: Headers;
};

export type loginUserResponse =
  | loginUserResponseSuccess
  | loginUserResponseError;

export const getLoginUserUrl = () => {
  return `/api/v1/users/login`;
};

/**
 * @summary Log in a user and return an access token
 */
export const loginUser = async (
  loginRequest?: LoginRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<loginUserResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<loginUserResponse>(getLoginUserUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(loginRequest),
  });
};

export const getLoginUserMutationKey = () => ["loginUser"] as const;

export const getLoginUserMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    LoginUserMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  LoginUserMutationVariables,
  TContext
> => {
  const mutationKey = getLoginUserMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    LoginUserMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return loginUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUser>>
>;
export type LoginUserMutationBody = LoginRequest | undefined;
export type LoginUserMutationError = ApiErrorResponse;
export type LoginUserMutationVariables = { data?: LoginRequest };

/**
 * @summary Log in a user and return an access token
 */
export const useLoginUser = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginUser>>,
      TError,
      LoginUserMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  LoginUserMutationVariables,
  TContext
> => {
  return useMutation(getLoginUserMutationOptions(options), queryClient);
};
export type getLoggedUserProfileResponse200 = {
  data: GetLoggedUserProfile200;
  status: 200;
};

export type getLoggedUserProfileResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type getLoggedUserProfileResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type getLoggedUserProfileResponseSuccess =
  getLoggedUserProfileResponse200 & {
    headers: Headers;
  };
export type getLoggedUserProfileResponseError = (
  | getLoggedUserProfileResponse401
  | getLoggedUserProfileResponse404
) & {
  headers: Headers;
};

export type getLoggedUserProfileResponse =
  | getLoggedUserProfileResponseSuccess
  | getLoggedUserProfileResponseError;

export const getGetLoggedUserProfileUrl = () => {
  return `/api/v1/users/profile`;
};

/**
 * @summary Get the profile of the logged-in user
 */
export const getLoggedUserProfile = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getLoggedUserProfileResponse> => {
  return customFetch<getLoggedUserProfileResponse>(
    getGetLoggedUserProfileUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetLoggedUserProfileQueryKey = () => {
  return [`/api/v1/users/profile`] as const;
};

export const getGetLoggedUserProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getLoggedUserProfile>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getLoggedUserProfile>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLoggedUserProfileQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLoggedUserProfile>>
  > = ({ signal }) => getLoggedUserProfile({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLoggedUserProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLoggedUserProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLoggedUserProfile>>
>;
export type GetLoggedUserProfileQueryError = ApiErrorResponse;

export function useGetLoggedUserProfile<
  TData = Awaited<ReturnType<typeof getLoggedUserProfile>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLoggedUserProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoggedUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getLoggedUserProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLoggedUserProfile<
  TData = Awaited<ReturnType<typeof getLoggedUserProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLoggedUserProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoggedUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getLoggedUserProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLoggedUserProfile<
  TData = Awaited<ReturnType<typeof getLoggedUserProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLoggedUserProfile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the profile of the logged-in user
 */

export function useGetLoggedUserProfile<
  TData = Awaited<ReturnType<typeof getLoggedUserProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLoggedUserProfile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLoggedUserProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateProfileResponse200 = {
  data: UpdateProfile200;
  status: 200;
};

export type updateProfileResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type updateProfileResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type updateProfileResponse409 = {
  data: ApiErrorResponse;
  status: 409;
};

export type updateProfileResponseSuccess = updateProfileResponse200 & {
  headers: Headers;
};
export type updateProfileResponseError = (
  | updateProfileResponse400
  | updateProfileResponse401
  | updateProfileResponse409
) & {
  headers: Headers;
};

export type updateProfileResponse =
  | updateProfileResponseSuccess
  | updateProfileResponseError;

export const getUpdateProfileUrl = () => {
  return `/api/v1/users/profile`;
};

/**
 * @summary Update the logged-in user's profile
 */
export const updateProfile = async (
  updateProfileRequest?: UpdateProfileRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<updateProfileResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<updateProfileResponse>(getUpdateProfileUrl(), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(updateProfileRequest),
  });
};

export const getUpdateProfileMutationKey = () => ["updateProfile"] as const;

export const getUpdateProfileMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    UpdateProfileMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  UpdateProfileMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateProfileMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProfile>>,
    UpdateProfileMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return updateProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProfile>>
>;
export type UpdateProfileMutationBody = UpdateProfileRequest | undefined;
export type UpdateProfileMutationError = ApiErrorResponse;
export type UpdateProfileMutationVariables = { data?: UpdateProfileRequest };

/**
 * @summary Update the logged-in user's profile
 */
export const useUpdateProfile = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProfile>>,
      TError,
      UpdateProfileMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  UpdateProfileMutationVariables,
  TContext
> => {
  return useMutation(getUpdateProfileMutationOptions(options), queryClient);
};
export type getUserProfileResponse200 = {
  data: GetUserProfile200;
  status: 200;
};

export type getUserProfileResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type getUserProfileResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type getUserProfileResponseSuccess = getUserProfileResponse200 & {
  headers: Headers;
};
export type getUserProfileResponseError = (
  | getUserProfileResponse400
  | getUserProfileResponse404
) & {
  headers: Headers;
};

export type getUserProfileResponse =
  | getUserProfileResponseSuccess
  | getUserProfileResponseError;

export const getGetUserProfileUrl = (userId: number) => {
  return `/api/v1/users/profile/${userId}`;
};

/**
 * @summary Get a user's profile by ID
 */
export const getUserProfile = async (
  userId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<getUserProfileResponse> => {
  return customFetch<getUserProfileResponse>(getGetUserProfileUrl(userId), {
    ...options,
    method: "GET",
  });
};

export const getGetUserProfileQueryKey = (userId: number) => {
  return [`/api/v1/users/profile/${userId}`] as const;
};

export const getGetUserProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserProfile>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserProfileQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProfile>>> = ({
    signal,
  }) => getUserProfile(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserProfile>>
>;
export type GetUserProfileQueryError = ApiErrorResponse;

export function useGetUserProfile<
  TData = Awaited<ReturnType<typeof getUserProfile>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getUserProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserProfile<
  TData = Awaited<ReturnType<typeof getUserProfile>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getUserProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserProfile<
  TData = Awaited<ReturnType<typeof getUserProfile>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a user's profile by ID
 */

export function useGetUserProfile<
  TData = Awaited<ReturnType<typeof getUserProfile>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserProfileQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getUserRoleResponse200 = {
  data: GetUserRole200;
  status: 200;
};

export type getUserRoleResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type getUserRoleResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type getUserRoleResponseSuccess = getUserRoleResponse200 & {
  headers: Headers;
};
export type getUserRoleResponseError = (
  | getUserRoleResponse400
  | getUserRoleResponse404
) & {
  headers: Headers;
};

export type getUserRoleResponse =
  | getUserRoleResponseSuccess
  | getUserRoleResponseError;

export const getGetUserRoleUrl = (userId: number) => {
  return `/api/v1/users/role/${userId}`;
};

/**
 * @summary Get a user's role by ID
 */
export const getUserRole = async (
  userId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<getUserRoleResponse> => {
  return customFetch<getUserRoleResponse>(getGetUserRoleUrl(userId), {
    ...options,
    method: "GET",
  });
};

export const getGetUserRoleQueryKey = (userId: number) => {
  return [`/api/v1/users/role/${userId}`] as const;
};

export const getGetUserRoleQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserRole>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserRole>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserRoleQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserRole>>> = ({
    signal,
  }) => getUserRole(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserRole>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserRoleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserRole>>
>;
export type GetUserRoleQueryError = ApiErrorResponse;

export function useGetUserRole<
  TData = Awaited<ReturnType<typeof getUserRole>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserRole>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRole>>,
          TError,
          Awaited<ReturnType<typeof getUserRole>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserRole<
  TData = Awaited<ReturnType<typeof getUserRole>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserRole>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRole>>,
          TError,
          Awaited<ReturnType<typeof getUserRole>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserRole<
  TData = Awaited<ReturnType<typeof getUserRole>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserRole>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a user's role by ID
 */

export function useGetUserRole<
  TData = Awaited<ReturnType<typeof getUserRole>>,
  TError = ApiErrorResponse,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserRole>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserRoleQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type changeUserRoleResponse200 = {
  data: ChangeUserRole200;
  status: 200;
};

export type changeUserRoleResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type changeUserRoleResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type changeUserRoleResponse403 = {
  data: ApiErrorResponse;
  status: 403;
};

export type changeUserRoleResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type changeUserRoleResponseSuccess = changeUserRoleResponse200 & {
  headers: Headers;
};
export type changeUserRoleResponseError = (
  | changeUserRoleResponse400
  | changeUserRoleResponse401
  | changeUserRoleResponse403
  | changeUserRoleResponse404
) & {
  headers: Headers;
};

export type changeUserRoleResponse =
  | changeUserRoleResponseSuccess
  | changeUserRoleResponseError;

export const getChangeUserRoleUrl = (userId: number) => {
  return `/api/v1/users/role/${userId}`;
};

/**
 * @summary Change a user's role (requires sufficient privileges)
 */
export const changeUserRole = async (
  userId: number,
  changeRoleRequest?: ChangeRoleRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<changeUserRoleResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<changeUserRoleResponse>(getChangeUserRoleUrl(userId), {
    ...options,
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(changeRoleRequest),
  });
};

export const getChangeUserRoleMutationKey = () => ["changeUserRole"] as const;

export const getChangeUserRoleMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeUserRole>>,
    TError,
    ChangeUserRoleMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeUserRole>>,
  TError,
  ChangeUserRoleMutationVariables,
  TContext
> => {
  const mutationKey = getChangeUserRoleMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeUserRole>>,
    ChangeUserRoleMutationVariables
  > = (props) => {
    const { userId, data } = props ?? {};

    return changeUserRole(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangeUserRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof changeUserRole>>
>;
export type ChangeUserRoleMutationBody = ChangeRoleRequest | undefined;
export type ChangeUserRoleMutationError = ApiErrorResponse;
export type ChangeUserRoleMutationVariables = {
  userId: number;
  data?: ChangeRoleRequest;
};

/**
 * @summary Change a user's role (requires sufficient privileges)
 */
export const useChangeUserRole = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeUserRole>>,
      TError,
      ChangeUserRoleMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof changeUserRole>>,
  TError,
  ChangeUserRoleMutationVariables,
  TContext
> => {
  return useMutation(getChangeUserRoleMutationOptions(options), queryClient);
};
