/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
export interface ApiErrorResponse {
  success: boolean;
  message: string;
  errors?: unknown | null;
}

export interface RegisterRequest {
  /**
   * User's username (max 30 characters)
   * @maxLength 30
   */
  username: string;
  /** User's email address */
  email: string;
  /**
   * User's password (min 8 characters)
   * @minLength 8
   */
  password: string;
  /**
   * User bio
   * @nullable
   */
  bio?: string | null;
  /**
   * URL of the user's avatar
   * @nullable
   */
  avatar_url?: string | null;
}

export interface LoginRequest {
  /** User's email address */
  email: string;
  /**
   * User's password (min 8 characters)
   * @minLength 8
   */
  password: string;
}

/**
 * User role
 */
export type ChangeRoleRequestNewRole =
  (typeof ChangeRoleRequestNewRole)[keyof typeof ChangeRoleRequestNewRole];

export const ChangeRoleRequestNewRole = {
  superadmin: "superadmin",
  admin: "admin",
  moderator: "moderator",
  normal: "normal",
} as const;

export interface ChangeRoleRequest {
  /** User role */
  new_role: ChangeRoleRequestNewRole;
}

export interface UpdateProfileRequest {
  /**
   * User's username (max 30 characters)
   * @maxLength 30
   * @nullable
   */
  username?: string | null;
  /**
   * User bio
   * @nullable
   */
  bio?: string | null;
  /**
   * URL of the user's avatar
   * @nullable
   */
  avatar_url?: string | null;
}

/**
 * User role
 */
export type UserProfileRole =
  (typeof UserProfileRole)[keyof typeof UserProfileRole];

export const UserProfileRole = {
  superadmin: "superadmin",
  admin: "admin",
  moderator: "moderator",
  normal: "normal",
} as const;

export interface UserProfile {
  /**
   * User ID
   * @exclusiveMinimum 0
   */
  user_id: number;
  /**
   * User's username (max 30 characters)
   * @maxLength 30
   */
  username: string;
  /** User's email address */
  email: string;
  /** @nullable */
  bio: string | null;
  /** @nullable */
  avatar_url: string | null;
  /** User role */
  role: UserProfileRole;
  created_at: string;
}

/**
 * User role
 */
export type UserRoleResponseRole =
  (typeof UserRoleResponseRole)[keyof typeof UserRoleResponseRole];

export const UserRoleResponseRole = {
  superadmin: "superadmin",
  admin: "admin",
  moderator: "moderator",
  normal: "normal",
} as const;

export interface UserRoleResponse {
  /** User role */
  role: UserRoleResponseRole;
}

/**
 * Problem difficulty level
 */
export type CreateProblemRequestDifficulty =
  (typeof CreateProblemRequestDifficulty)[keyof typeof CreateProblemRequestDifficulty];

export const CreateProblemRequestDifficulty = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
} as const;

export interface CreateProblemRequest {
  /**
   * Problem title (max 200 characters)
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * S3 key for problem statement markdown
   * @minLength 1
   */
  markdown_key: string;
  /**
   * Array of S3 keys for test cases
   * @minItems 1
   * @items.minLength 1
   */
  test_keys: string[];
  /** Problem difficulty level */
  difficulty: CreateProblemRequestDifficulty;
  /**
   * Problem tags
   * @nullable
   * @items.minLength 1
   */
  tags?: string[] | null;
}

/**
 * Problem difficulty level
 * @nullable
 */
export type UpdateProblemRequestDifficulty =
  | (typeof UpdateProblemRequestDifficulty)[keyof typeof UpdateProblemRequestDifficulty]
  | null;

export const UpdateProblemRequestDifficulty = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
} as const;

export interface UpdateProblemRequest {
  /**
   * Problem title (max 200 characters)
   * @minLength 1
   * @maxLength 200
   * @nullable
   */
  title?: string | null;
  /**
   * S3 key for problem statement markdown
   * @minLength 1
   * @nullable
   */
  markdown_key?: string | null;
  /**
   * Array of S3 keys for test cases
   * @minItems 1
   * @nullable
   * @items.minLength 1
   */
  test_keys?: string[] | null;
  /**
   * Problem difficulty level
   * @nullable
   */
  difficulty?: UpdateProblemRequestDifficulty;
  /**
   * Problem tags
   * @nullable
   * @items.minLength 1
   */
  tags?: string[] | null;
}

/**
 * Problem difficulty level
 */
export type ProblemDifficulty =
  (typeof ProblemDifficulty)[keyof typeof ProblemDifficulty];

export const ProblemDifficulty = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
} as const;

export interface Problem {
  /** Problem UUID */
  problem_id: string;
  /**
   * Problem title (max 200 characters)
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * S3 key for problem statement markdown
   * @minLength 1
   */
  markdown_key: string;
  /**
   * Array of S3 keys for test cases
   * @minItems 1
   * @items.minLength 1
   */
  test_keys: string[];
  /** Problem difficulty level */
  difficulty: ProblemDifficulty;
  tags: string[];
  /**
   * User ID
   * @exclusiveMinimum 0
   */
  created_by: number;
  created_at: string;
  updated_at: string;
}

export type ProblemWithCreator = Problem & {
  /**
   * User's username (max 30 characters)
   * @maxLength 30
   */
  creator_username: string;
};

export interface GetProblemsResponse {
  problems: ProblemWithCreator[];
  totalProblems: number;
  totalPages: number;
  currentPage: number;
}

/**
 * Programming language
 */
export type CreateSubmissionRequestLanguage =
  (typeof CreateSubmissionRequestLanguage)[keyof typeof CreateSubmissionRequestLanguage];

export const CreateSubmissionRequestLanguage = {
  cpp: "cpp",
} as const;

export interface CreateSubmissionRequest {
  /**
   * Target problem ID
   * @minLength 1
   */
  problem_id: string;
  /** Programming language */
  language: CreateSubmissionRequestLanguage;
  /**
   * Blob/object storage key of submitted code
   * @minLength 1
   */
  submission_key: string;
}

/**
 * Programming language
 */
export type SubmissionLanguage =
  (typeof SubmissionLanguage)[keyof typeof SubmissionLanguage];

export const SubmissionLanguage = {
  cpp: "cpp",
} as const;

/**
 * Submission status
 */
export type SubmissionStatus =
  (typeof SubmissionStatus)[keyof typeof SubmissionStatus];

export const SubmissionStatus = {
  queued: "queued",
  compile_error: "compile_error",
  runtime_error: "runtime_error",
  time_limit_exceeded: "time_limit_exceeded",
  wrong_answer: "wrong_answer",
  successful: "successful",
  server_error: "server_error",
} as const;

export interface Submission {
  submission_id: number;
  /**
   * User ID
   * @exclusiveMinimum 0
   */
  user_id: number;
  problem_id: string;
  /**
   * Blob/object storage key of submitted code
   * @minLength 1
   */
  submission_key: string;
  /** Programming language */
  language: SubmissionLanguage;
  /** Submission status */
  status: SubmissionStatus;
  executed_at: string | unknown | null;
  completed_at: string | unknown | null;
  created_at: string;
  updated_at: string;
}

export interface GetSubmissionsResponse {
  submissions: Submission[];
  totalSubmissions: number;
  totalPages: number;
  currentPage: number;
}

/**
 * Registration successful response
 */
export type RegisterUser201 = {
  success: boolean;
  message: string;
  errors?: unknown | null;
};

/**
 * Login successful response
 */
export type LoginUser200 = {
  success: boolean;
  message: string;
  errors?: unknown | null;
};

export type GetLoggedUserProfile200 = {
  success: boolean;
  message: string;
  data: UserProfile;
  errors?: unknown | null;
};

/**
 * Profile update response
 */
export type UpdateProfile200 = {
  success: boolean;
  message: string;
  errors?: unknown | null;
};

export type GetUserProfile200 = {
  success: boolean;
  message: string;
  data: UserProfile;
  errors?: unknown | null;
};

export type GetUserRole200 = {
  success: boolean;
  message: string;
  data: UserRoleResponse;
  errors?: unknown | null;
};

/**
 * Role change response
 */
export type ChangeUserRole200 = {
  success: boolean;
  message: string;
  errors?: unknown | null;
};

export type CreateProblem201 = {
  success: boolean;
  message: string;
  data: Problem;
  errors?: unknown | null;
};

export type GetProblemsParams = {
  /**
   * Page number for pagination
   * @exclusiveMinimum 0
   */
  page?: number;
  /**
   * Number of problems per page
   * @maximum 50
   * @exclusiveMinimum 0
   */
  limit?: number;
  /**
   * Filter by difficulty
   * @nullable
   */
  difficulty?: GetProblemsDifficulty;
  /**
   * Comma-separated list of tags to filter by
   * @nullable
   * @items.minLength 1
   */
  tags?: string[] | null;
  /**
   * Search in problem titles
   * @nullable
   */
  search?: string | null;
  /**
   * Filter by creator user ID
   * @exclusiveMinimum 0
   * @nullable
   */
  created_by?: number | null;
};

export type GetProblemsDifficulty =
  | (typeof GetProblemsDifficulty)[keyof typeof GetProblemsDifficulty]
  | null;

export const GetProblemsDifficulty = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
} as const;

export type GetProblems200 = {
  success: boolean;
  message: string;
  data: GetProblemsResponse;
  errors?: unknown | null;
};

export type GetProblem200 = {
  success: boolean;
  message: string;
  data: ProblemWithCreator;
  errors?: unknown | null;
};

export type UpdateProblem200 = {
  success: boolean;
  message: string;
  data: Problem;
  errors?: unknown | null;
};

/**
 * Problem delete response
 */
export type DeleteProblem200 = {
  success: boolean;
  message: string;
  errors?: unknown | null;
};

export type CreateSubmission201 = {
  success: boolean;
  message: string;
  data: Submission;
  errors?: unknown | null;
};

export type GetSubmissionsParams = {
  /**
   * @exclusiveMinimum 0
   */
  page?: number;
  /**
   * @maximum 50
   * @exclusiveMinimum 0
   */
  limit?: number;
  /**
   * Filter by problem ID (provide problemId or userId)
   * @minLength 1
   * @nullable
   */
  problemId?: string | null;
  /**
   * Filter by user ID (provide problemId or userId)
   * @exclusiveMinimum 0
   * @nullable
   */
  userId?: number | null;
  /**
   * Submission status
   * @nullable
   */
  status?: GetSubmissionsStatus;
  /**
   * Programming language
   * @nullable
   */
  language?: GetSubmissionsLanguage;
};

export type GetSubmissionsStatus =
  | (typeof GetSubmissionsStatus)[keyof typeof GetSubmissionsStatus]
  | null;

export const GetSubmissionsStatus = {
  queued: "queued",
  compile_error: "compile_error",
  runtime_error: "runtime_error",
  time_limit_exceeded: "time_limit_exceeded",
  wrong_answer: "wrong_answer",
  successful: "successful",
  server_error: "server_error",
} as const;

export type GetSubmissionsLanguage =
  | (typeof GetSubmissionsLanguage)[keyof typeof GetSubmissionsLanguage]
  | null;

export const GetSubmissionsLanguage = {
  cpp: "cpp",
} as const;

export type GetSubmissions200 = {
  success: boolean;
  message: string;
  data: GetSubmissionsResponse;
  errors?: unknown | null;
};

export type GetJwks200KeysItem = { [key: string]: unknown | null };

export type GetJwks200 = {
  keys: GetJwks200KeysItem[];
};
