import {
  Generated,
  ColumnType,
  Selectable,
  Insertable,
  Updateable,
} from "kysely";
import { User, UserTable } from "./user.model";

////////////////////////////////////////////
// Problem Difficulty
////////////////////////////////////////////
export const ProblemDifficulty = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type ProblemDifficulty =
  (typeof ProblemDifficulty)[keyof typeof ProblemDifficulty];

////////////////////////////////////////////
// Problem Table Definition
// Postgres will convert all column names to lowercase
// Hence using snake case for database columns
// Reference: https://kysely.dev/docs/getting-started
////////////////////////////////////////////
export interface ProblemTable {
  problem_id: Generated<string>; // UUID generated by database
  title: string;
  /**
   * S3 key for problem statement markdown
   * Why not store markdown content directly in the database?
   * - Markdown may reference images
   * - So instead of managing them separately, we can store the image as base-64 in the markdown itself
   * - Storing such large markdown in DB will be inefficient
   */
  markdown_key: string;
  test_keys: string[]; // Array of S3 keys for test cases
  difficulty: ProblemDifficulty;
  tags: string[]; // Array of problem tags
  created_by: UserTable["user_id"]; // Foreign key to users table
  created_at: ColumnType<Date, never, never>;
  updated_at: ColumnType<Date, string | undefined, string>;
}

export type Problem = Selectable<ProblemTable>;
export type NewProblem = Insertable<ProblemTable>;
export type ProblemUpdate = Updateable<ProblemTable>;

////////////////////////////////////////////
// Joined Types
////////////////////////////////////////////
export interface ProblemWithCreator extends Problem {
  creator_username: User["username"];
}
