/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary Register a new user
 */
export const registerUserBodyUsernameMax = 30;

export const registerUserBodyPasswordMin = 8;

export const RegisterUserBody = zod.object({
  username: zod
    .string()
    .max(registerUserBodyUsernameMax)
    .describe("User's username (max 30 characters)"),
  email: zod.email().describe("User's email address"),
  password: zod
    .string()
    .min(registerUserBodyPasswordMin)
    .describe("User's password (min 8 characters)"),
  bio: zod.string().nullish().describe("User bio"),
  avatar_url: zod.string().nullish().describe("URL of the user's avatar"),
});

export const RegisterUserResponse = zod
  .object({
    success: zod.boolean(),
    message: zod.string(),
    errors: zod.unknown().nullish(),
  })
  .describe("Registration successful response");

/**
 * @summary Log in a user and return an access token
 */
export const loginUserBodyPasswordMin = 8;

export const LoginUserBody = zod.object({
  email: zod.email().describe("User's email address"),
  password: zod
    .string()
    .min(loginUserBodyPasswordMin)
    .describe("User's password (min 8 characters)"),
});

export const LoginUserResponse = zod
  .object({
    success: zod.boolean(),
    message: zod.string(),
    errors: zod.unknown().nullish(),
  })
  .describe("Login successful response");

/**
 * @summary Get the profile of the logged-in user
 */
export const getLoggedUserProfileResponseDataUserIdExclusiveMin = 0;

export const getLoggedUserProfileResponseDataUsernameMax = 30;

export const GetLoggedUserProfileResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    user_id: zod
      .int()
      .gt(getLoggedUserProfileResponseDataUserIdExclusiveMin)
      .describe("User ID"),
    username: zod
      .string()
      .max(getLoggedUserProfileResponseDataUsernameMax)
      .describe("User's username (max 30 characters)"),
    email: zod.email().describe("User's email address"),
    bio: zod.string().nullable(),
    avatar_url: zod.string().nullable(),
    role: zod
      .enum(["superadmin", "admin", "moderator", "normal"])
      .describe("User role"),
    created_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
  }),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Update the logged-in user's profile
 */
export const updateProfileBodyUsernameMax = 30;

export const UpdateProfileBody = zod.object({
  username: zod
    .string()
    .max(updateProfileBodyUsernameMax)
    .nullish()
    .describe("User's username (max 30 characters)"),
  bio: zod.string().nullish().describe("User bio"),
  avatar_url: zod.string().nullish().describe("URL of the user's avatar"),
});

export const UpdateProfileResponse = zod
  .object({
    success: zod.boolean(),
    message: zod.string(),
    errors: zod.unknown().nullish(),
  })
  .describe("Profile update response");

/**
 * @summary Get a user's profile by ID
 */
export const getUserProfilePathUserIdExclusiveMin = 0;

export const GetUserProfileParams = zod.object({
  userId: zod
    .int()
    .gt(getUserProfilePathUserIdExclusiveMin)
    .describe("The ID of the user to fetch"),
});

export const getUserProfileResponseDataUserIdExclusiveMin = 0;

export const getUserProfileResponseDataUsernameMax = 30;

export const GetUserProfileResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    user_id: zod
      .int()
      .gt(getUserProfileResponseDataUserIdExclusiveMin)
      .describe("User ID"),
    username: zod
      .string()
      .max(getUserProfileResponseDataUsernameMax)
      .describe("User's username (max 30 characters)"),
    email: zod.email().describe("User's email address"),
    bio: zod.string().nullable(),
    avatar_url: zod.string().nullable(),
    role: zod
      .enum(["superadmin", "admin", "moderator", "normal"])
      .describe("User role"),
    created_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
  }),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Get a user's role by ID
 */
export const getUserRolePathUserIdExclusiveMin = 0;

export const GetUserRoleParams = zod.object({
  userId: zod
    .int()
    .gt(getUserRolePathUserIdExclusiveMin)
    .describe("The ID of the user whose role is to be fetched"),
});

export const GetUserRoleResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    role: zod
      .enum(["superadmin", "admin", "moderator", "normal"])
      .describe("User role"),
  }),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Change a user's role (requires sufficient privileges)
 */
export const changeUserRolePathUserIdExclusiveMin = 0;

export const ChangeUserRoleParams = zod.object({
  userId: zod
    .int()
    .gt(changeUserRolePathUserIdExclusiveMin)
    .describe("The ID of the user whose role is to be changed"),
});

export const ChangeUserRoleBody = zod.object({
  new_role: zod
    .enum(["superadmin", "admin", "moderator", "normal"])
    .describe("User role"),
});

export const ChangeUserRoleResponse = zod
  .object({
    success: zod.boolean(),
    message: zod.string(),
    errors: zod.unknown().nullish(),
  })
  .describe("Role change response");
