/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary Create a new code submission
 */

export const CreateSubmissionBody = zod.object({
  problem_id: zod.string().min(1).describe("Target problem ID"),
  language: zod.enum(["cpp"]).describe("Programming language"),
  submission_key: zod
    .string()
    .min(1)
    .describe("Blob/object storage key of submitted code"),
});

export const createSubmissionResponseDataUserIdExclusiveMin = 0;

export const CreateSubmissionResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    submission_id: zod.int(),
    user_id: zod
      .int()
      .gt(createSubmissionResponseDataUserIdExclusiveMin)
      .describe("User ID"),
    problem_id: zod.string(),
    submission_key: zod
      .string()
      .min(1)
      .describe("Blob/object storage key of submitted code"),
    language: zod.enum(["cpp"]).describe("Programming language"),
    status: zod
      .enum([
        "queued",
        "compile_error",
        "runtime_error",
        "time_limit_exceeded",
        "wrong_answer",
        "successful",
        "server_error",
      ])
      .describe("Submission status"),
    executed_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
      zod.unknown().nullable(),
    ]),
    completed_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
      zod.unknown().nullable(),
    ]),
    created_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
    updated_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
  }),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Get submissions by problemId or userId
 */
export const getSubmissionsQueryPageDefault = 1;
export const getSubmissionsQueryPageExclusiveMin = 0;

export const getSubmissionsQueryLimitDefault = 10;
export const getSubmissionsQueryLimitExclusiveMin = 0;
export const getSubmissionsQueryLimitMax = 50;

export const getSubmissionsQueryUserIdExclusiveMin = 0;

export const GetSubmissionsQueryParams = zod.object({
  page: zod
    .int()
    .gt(getSubmissionsQueryPageExclusiveMin)
    .default(getSubmissionsQueryPageDefault),
  limit: zod
    .int()
    .gt(getSubmissionsQueryLimitExclusiveMin)
    .max(getSubmissionsQueryLimitMax)
    .default(getSubmissionsQueryLimitDefault),
  problemId: zod
    .string()
    .min(1)
    .nullish()
    .describe("Filter by problem ID (provide problemId or userId)"),
  userId: zod
    .int()
    .gt(getSubmissionsQueryUserIdExclusiveMin)
    .nullish()
    .describe("Filter by user ID (provide problemId or userId)"),
  status: zod
    .union([
      zod.literal("queued"),
      zod.literal("compile_error"),
      zod.literal("runtime_error"),
      zod.literal("time_limit_exceeded"),
      zod.literal("wrong_answer"),
      zod.literal("successful"),
      zod.literal("server_error"),
      zod.literal(null),
    ])
    .nullish()
    .describe("Submission status"),
  language: zod
    .union([zod.literal("cpp"), zod.literal(null)])
    .nullish()
    .describe("Programming language"),
});

export const getSubmissionsResponseDataSubmissionsItemUserIdExclusiveMin = 0;

export const GetSubmissionsResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    submissions: zod.array(
      zod.object({
        submission_id: zod.int(),
        user_id: zod
          .int()
          .gt(getSubmissionsResponseDataSubmissionsItemUserIdExclusiveMin)
          .describe("User ID"),
        problem_id: zod.string(),
        submission_key: zod
          .string()
          .min(1)
          .describe("Blob/object storage key of submitted code"),
        language: zod.enum(["cpp"]).describe("Programming language"),
        status: zod
          .enum([
            "queued",
            "compile_error",
            "runtime_error",
            "time_limit_exceeded",
            "wrong_answer",
            "successful",
            "server_error",
          ])
          .describe("Submission status"),
        executed_at: zod.union([
          zod.iso.datetime({ offset: true }),
          zod.iso.datetime({ offset: true }),
          zod.unknown().nullable(),
        ]),
        completed_at: zod.union([
          zod.iso.datetime({ offset: true }),
          zod.iso.datetime({ offset: true }),
          zod.unknown().nullable(),
        ]),
        created_at: zod.union([
          zod.iso.datetime({ offset: true }),
          zod.iso.datetime({ offset: true }),
        ]),
        updated_at: zod.union([
          zod.iso.datetime({ offset: true }),
          zod.iso.datetime({ offset: true }),
        ]),
      }),
    ),
    totalSubmissions: zod.int(),
    totalPages: zod.int(),
    currentPage: zod.int(),
  }),
  errors: zod.unknown().nullish(),
});
