/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary Get JSON Web Key Set (JWKS)
 */
export const GetJwksResponse = zod.object({
  keys: zod.array(zod.record(zod.string(), zod.unknown().nullable())),
});
