/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetJwks200 } from "../discodeApi.schemas.ts";

import { customFetch } from ".././fetcher.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getJwksResponse200 = {
  data: GetJwks200;
  status: 200;
};

export type getJwksResponseSuccess = getJwksResponse200 & {
  headers: Headers;
};
export type getJwksResponse = getJwksResponseSuccess;

export const getGetJwksUrl = () => {
  return `/api/v1/jwks`;
};

/**
 * @summary Get JSON Web Key Set (JWKS)
 */
export const getJwks = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getJwksResponse> => {
  return customFetch<getJwksResponse>(getGetJwksUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetJwksQueryKey = () => {
  return [`/api/v1/jwks`] as const;
};

export const getGetJwksQueryOptions = <
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetJwksQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getJwks>>> = ({
    signal,
  }) => getJwks({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getJwks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetJwksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getJwks>>
>;
export type GetJwksQueryError = unknown;

export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJwks>>,
          TError,
          Awaited<ReturnType<typeof getJwks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJwks>>,
          TError,
          Awaited<ReturnType<typeof getJwks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get JSON Web Key Set (JWKS)
 */

export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetJwksQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
