/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type { GetJwks200 } from "../discodeApi.schemas";

export const getGetJwksResponseMock = (
  overrideResponse: Partial<Extract<GetJwks200, object>> = {},
): GetJwks200 => ({
  keys: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    [faker.string.alphanumeric(5)]: faker.helpers.arrayElement([{}, null]),
  })),
  ...overrideResponse,
});
