/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary Create a new problem
 */
export const createProblemBodyTitleMax = 200;

export const CreateProblemBody = zod.object({
  title: zod
    .string()
    .min(1)
    .max(createProblemBodyTitleMax)
    .describe("Problem title (max 200 characters)"),
  markdown_key: zod
    .string()
    .min(1)
    .describe("S3 key for problem statement markdown"),
  test_keys: zod
    .array(zod.string().min(1).describe("S3 key for file storage"))
    .min(1)
    .describe("Array of S3 keys for test cases"),
  difficulty: zod
    .enum(["easy", "medium", "hard"])
    .describe("Problem difficulty level"),
  tags: zod.array(zod.string().min(1)).nullish().describe("Problem tags"),
});

export const createProblemResponseDataTitleMax = 200;

export const createProblemResponseDataCreatedByExclusiveMin = 0;

export const CreateProblemResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    problem_id: zod.uuid().describe("Problem UUID"),
    title: zod
      .string()
      .min(1)
      .max(createProblemResponseDataTitleMax)
      .describe("Problem title (max 200 characters)"),
    markdown_key: zod
      .string()
      .min(1)
      .describe("S3 key for problem statement markdown"),
    test_keys: zod
      .array(zod.string().min(1).describe("S3 key for file storage"))
      .min(1)
      .describe("Array of S3 keys for test cases"),
    difficulty: zod
      .enum(["easy", "medium", "hard"])
      .describe("Problem difficulty level"),
    tags: zod.array(zod.string()),
    created_by: zod
      .int()
      .gt(createProblemResponseDataCreatedByExclusiveMin)
      .describe("User ID"),
    created_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
    updated_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
  }),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Get problems with optional filtering and pagination
 */
export const getProblemsQueryPageDefault = 1;
export const getProblemsQueryPageExclusiveMin = 0;

export const getProblemsQueryLimitDefault = 10;
export const getProblemsQueryLimitExclusiveMin = 0;
export const getProblemsQueryLimitMax = 50;

export const getProblemsQueryCreatedByExclusiveMin = 0;

export const GetProblemsQueryParams = zod.object({
  page: zod
    .int()
    .gt(getProblemsQueryPageExclusiveMin)
    .default(getProblemsQueryPageDefault)
    .describe("Page number for pagination"),
  limit: zod
    .int()
    .gt(getProblemsQueryLimitExclusiveMin)
    .max(getProblemsQueryLimitMax)
    .default(getProblemsQueryLimitDefault)
    .describe("Number of problems per page"),
  difficulty: zod
    .union([
      zod.literal("easy"),
      zod.literal("medium"),
      zod.literal("hard"),
      zod.literal(null),
    ])
    .nullish()
    .describe("Filter by difficulty"),
  tags: zod
    .array(zod.string().min(1))
    .nullish()
    .describe("Comma-separated list of tags to filter by"),
  search: zod.string().nullish().describe("Search in problem titles"),
  created_by: zod
    .int()
    .gt(getProblemsQueryCreatedByExclusiveMin)
    .nullish()
    .describe("Filter by creator user ID"),
});

export const getProblemsResponseDataProblemsItemOneTitleMax = 200;

export const getProblemsResponseDataProblemsItemOneCreatedByExclusiveMin = 0;

export const getProblemsResponseDataProblemsItemTwoCreatorUsernameMax = 30;

export const GetProblemsResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    problems: zod.array(
      zod
        .object({
          problem_id: zod.uuid().describe("Problem UUID"),
          title: zod
            .string()
            .min(1)
            .max(getProblemsResponseDataProblemsItemOneTitleMax)
            .describe("Problem title (max 200 characters)"),
          markdown_key: zod
            .string()
            .min(1)
            .describe("S3 key for problem statement markdown"),
          test_keys: zod
            .array(zod.string().min(1).describe("S3 key for file storage"))
            .min(1)
            .describe("Array of S3 keys for test cases"),
          difficulty: zod
            .enum(["easy", "medium", "hard"])
            .describe("Problem difficulty level"),
          tags: zod.array(zod.string()),
          created_by: zod
            .int()
            .gt(getProblemsResponseDataProblemsItemOneCreatedByExclusiveMin)
            .describe("User ID"),
          created_at: zod.union([
            zod.iso.datetime({ offset: true }),
            zod.iso.datetime({ offset: true }),
          ]),
          updated_at: zod.union([
            zod.iso.datetime({ offset: true }),
            zod.iso.datetime({ offset: true }),
          ]),
        })
        .and(
          zod.object({
            creator_username: zod
              .string()
              .max(getProblemsResponseDataProblemsItemTwoCreatorUsernameMax)
              .describe("User's username (max 30 characters)"),
          }),
        ),
    ),
    totalProblems: zod.int(),
    totalPages: zod.int(),
    currentPage: zod.int(),
  }),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Get a problem by ID
 */
export const GetProblemParams = zod.object({
  problemId: zod.uuid().describe("Problem ID"),
});

export const getProblemResponseDataOneTitleMax = 200;

export const getProblemResponseDataOneCreatedByExclusiveMin = 0;

export const getProblemResponseDataTwoCreatorUsernameMax = 30;

export const GetProblemResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod
    .object({
      problem_id: zod.uuid().describe("Problem UUID"),
      title: zod
        .string()
        .min(1)
        .max(getProblemResponseDataOneTitleMax)
        .describe("Problem title (max 200 characters)"),
      markdown_key: zod
        .string()
        .min(1)
        .describe("S3 key for problem statement markdown"),
      test_keys: zod
        .array(zod.string().min(1).describe("S3 key for file storage"))
        .min(1)
        .describe("Array of S3 keys for test cases"),
      difficulty: zod
        .enum(["easy", "medium", "hard"])
        .describe("Problem difficulty level"),
      tags: zod.array(zod.string()),
      created_by: zod
        .int()
        .gt(getProblemResponseDataOneCreatedByExclusiveMin)
        .describe("User ID"),
      created_at: zod.union([
        zod.iso.datetime({ offset: true }),
        zod.iso.datetime({ offset: true }),
      ]),
      updated_at: zod.union([
        zod.iso.datetime({ offset: true }),
        zod.iso.datetime({ offset: true }),
      ]),
    })
    .and(
      zod.object({
        creator_username: zod
          .string()
          .max(getProblemResponseDataTwoCreatorUsernameMax)
          .describe("User's username (max 30 characters)"),
      }),
    ),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Update a problem
 */
export const UpdateProblemParams = zod.object({
  problemId: zod.uuid().describe("Problem ID"),
});

export const updateProblemBodyTitleMax = 200;

export const UpdateProblemBody = zod.object({
  title: zod
    .string()
    .min(1)
    .max(updateProblemBodyTitleMax)
    .nullish()
    .describe("Problem title (max 200 characters)"),
  markdown_key: zod
    .string()
    .min(1)
    .nullish()
    .describe("S3 key for problem statement markdown"),
  test_keys: zod
    .array(zod.string().min(1).describe("S3 key for file storage"))
    .min(1)
    .nullish()
    .describe("Array of S3 keys for test cases"),
  difficulty: zod
    .union([
      zod.literal("easy"),
      zod.literal("medium"),
      zod.literal("hard"),
      zod.literal(null),
    ])
    .nullish()
    .describe("Problem difficulty level"),
  tags: zod.array(zod.string().min(1)).nullish().describe("Problem tags"),
});

export const updateProblemResponseDataTitleMax = 200;

export const updateProblemResponseDataCreatedByExclusiveMin = 0;

export const UpdateProblemResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
  data: zod.object({
    problem_id: zod.uuid().describe("Problem UUID"),
    title: zod
      .string()
      .min(1)
      .max(updateProblemResponseDataTitleMax)
      .describe("Problem title (max 200 characters)"),
    markdown_key: zod
      .string()
      .min(1)
      .describe("S3 key for problem statement markdown"),
    test_keys: zod
      .array(zod.string().min(1).describe("S3 key for file storage"))
      .min(1)
      .describe("Array of S3 keys for test cases"),
    difficulty: zod
      .enum(["easy", "medium", "hard"])
      .describe("Problem difficulty level"),
    tags: zod.array(zod.string()),
    created_by: zod
      .int()
      .gt(updateProblemResponseDataCreatedByExclusiveMin)
      .describe("User ID"),
    created_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
    updated_at: zod.union([
      zod.iso.datetime({ offset: true }),
      zod.iso.datetime({ offset: true }),
    ]),
  }),
  errors: zod.unknown().nullish(),
});

/**
 * @summary Delete a problem
 */
export const DeleteProblemParams = zod.object({
  problemId: zod.uuid().describe("Problem ID"),
});

export const DeleteProblemResponse = zod
  .object({
    success: zod.boolean(),
    message: zod.string(),
    errors: zod.unknown().nullish(),
  })
  .describe("Problem delete response");
