/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type {
  CreateSubmission201,
  GetSubmissions200,
} from "../discodeApi.schemas";

export const getCreateSubmissionResponseMock = (
  overrideResponse: Partial<Extract<CreateSubmission201, object>> = {},
): CreateSubmission201 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    submission_id: faker.number.int(),
    user_id: faker.number.int({ min: 0 }),
    problem_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    submission_key: faker.string.alpha({ length: { min: 1, max: 20 } }),
    language: faker.helpers.arrayElement(["cpp"] as const),
    status: faker.helpers.arrayElement([
      "queued",
      "compile_error",
      "runtime_error",
      "time_limit_exceeded",
      "wrong_answer",
      "successful",
      "server_error",
    ] as const),
    executed_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
    completed_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
    created_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
    updated_at: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      faker.date.past().toISOString().slice(0, 19) + "Z",
    ]),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});

export const getGetSubmissionsResponseMock = (
  overrideResponse: Partial<Extract<GetSubmissions200, object>> = {},
): GetSubmissions200 => ({
  success: faker.datatype.boolean(),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data: {
    submissions: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      submission_id: faker.number.int(),
      user_id: faker.number.int({ min: 0 }),
      problem_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      submission_key: faker.string.alpha({ length: { min: 1, max: 20 } }),
      language: faker.helpers.arrayElement(["cpp"] as const),
      status: faker.helpers.arrayElement([
        "queued",
        "compile_error",
        "runtime_error",
        "time_limit_exceeded",
        "wrong_answer",
        "successful",
        "server_error",
      ] as const),
      executed_at: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        faker.date.past().toISOString().slice(0, 19) + "Z",
      ]),
      completed_at: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        faker.date.past().toISOString().slice(0, 19) + "Z",
      ]),
      created_at: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        faker.date.past().toISOString().slice(0, 19) + "Z",
      ]),
      updated_at: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        faker.date.past().toISOString().slice(0, 19) + "Z",
      ]),
    })),
    totalSubmissions: faker.number.int(),
    totalPages: faker.number.int(),
    currentPage: faker.number.int(),
  },
  errors: faker.helpers.arrayElement([
    faker.helpers.arrayElement([{}, null]),
    null,
  ]),
  ...overrideResponse,
});
