/**
 * Generated by orval 🍺
 * Do not edit manually.
 * discode-api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorResponse,
  CreateSubmission201,
  CreateSubmissionRequest,
  GetSubmissions200,
  GetSubmissionsParams,
} from "../discodeApi.schemas.ts";

import { customFetch } from ".././fetcher.ts";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createSubmissionResponse201 = {
  data: CreateSubmission201;
  status: 201;
};

export type createSubmissionResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type createSubmissionResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type createSubmissionResponse404 = {
  data: ApiErrorResponse;
  status: 404;
};

export type createSubmissionResponseSuccess = createSubmissionResponse201 & {
  headers: Headers;
};
export type createSubmissionResponseError = (
  | createSubmissionResponse400
  | createSubmissionResponse401
  | createSubmissionResponse404
) & {
  headers: Headers;
};

export type createSubmissionResponse =
  | createSubmissionResponseSuccess
  | createSubmissionResponseError;

export const getCreateSubmissionUrl = () => {
  return `/api/v1/submissions`;
};

/**
 * @summary Create a new code submission
 */
export const createSubmission = async (
  createSubmissionRequest?: CreateSubmissionRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<createSubmissionResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<createSubmissionResponse>(getCreateSubmissionUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(createSubmissionRequest),
  });
};

export const getCreateSubmissionMutationKey = () =>
  ["createSubmission"] as const;

export const getCreateSubmissionMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSubmission>>,
    TError,
    CreateSubmissionMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSubmission>>,
  TError,
  CreateSubmissionMutationVariables,
  TContext
> => {
  const mutationKey = getCreateSubmissionMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSubmission>>,
    CreateSubmissionMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createSubmission(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSubmissionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSubmission>>
>;
export type CreateSubmissionMutationBody = CreateSubmissionRequest | undefined;
export type CreateSubmissionMutationError = ApiErrorResponse;
export type CreateSubmissionMutationVariables = {
  data?: CreateSubmissionRequest;
};

/**
 * @summary Create a new code submission
 */
export const useCreateSubmission = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSubmission>>,
      TError,
      CreateSubmissionMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSubmission>>,
  TError,
  CreateSubmissionMutationVariables,
  TContext
> => {
  return useMutation(getCreateSubmissionMutationOptions(options), queryClient);
};
export type getSubmissionsResponse200 = {
  data: GetSubmissions200;
  status: 200;
};

export type getSubmissionsResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type getSubmissionsResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type getSubmissionsResponseSuccess = getSubmissionsResponse200 & {
  headers: Headers;
};
export type getSubmissionsResponseError = (
  | getSubmissionsResponse400
  | getSubmissionsResponse401
) & {
  headers: Headers;
};

export type getSubmissionsResponse =
  | getSubmissionsResponseSuccess
  | getSubmissionsResponseError;

export const getGetSubmissionsUrl = (params?: GetSubmissionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/submissions?${stringifiedParams}`
    : `/api/v1/submissions`;
};

/**
 * @summary Get submissions by problemId or userId
 */
export const getSubmissions = async (
  params?: GetSubmissionsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<getSubmissionsResponse> => {
  return customFetch<getSubmissionsResponse>(getGetSubmissionsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetSubmissionsQueryKey = (params?: GetSubmissionsParams) => {
  return [`/api/v1/submissions`, ...(params ? [params] : [])] as const;
};

export const getGetSubmissionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubmissions>>,
  TError = ApiErrorResponse,
>(
  params?: GetSubmissionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubmissions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubmissionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubmissions>>> = ({
    signal,
  }) => getSubmissions(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubmissions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSubmissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubmissions>>
>;
export type GetSubmissionsQueryError = ApiErrorResponse;

export function useGetSubmissions<
  TData = Awaited<ReturnType<typeof getSubmissions>>,
  TError = ApiErrorResponse,
>(
  params: undefined | GetSubmissionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubmissions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubmissions>>,
          TError,
          Awaited<ReturnType<typeof getSubmissions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSubmissions<
  TData = Awaited<ReturnType<typeof getSubmissions>>,
  TError = ApiErrorResponse,
>(
  params?: GetSubmissionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubmissions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubmissions>>,
          TError,
          Awaited<ReturnType<typeof getSubmissions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSubmissions<
  TData = Awaited<ReturnType<typeof getSubmissions>>,
  TError = ApiErrorResponse,
>(
  params?: GetSubmissionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubmissions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get submissions by problemId or userId
 */

export function useGetSubmissions<
  TData = Awaited<ReturnType<typeof getSubmissions>>,
  TError = ApiErrorResponse,
>(
  params?: GetSubmissionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubmissions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSubmissionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
